[package]
name = "dd-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
csv = "1.3.0"
dirs = "5.0.1"
structopt = "0.3.26"
tantivy = "0.21.1"